mysite/cryptocompare/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name ='cryptocompare'

urlpatterns = [
    path('', views.home, name='home'),
    
    path('register/', views.register, name='register'),
    path('crypto_login/', views.crypto_login, name='crypto_login'),
    path('crypto_list/', views.crypto_list, name='crypto_list'),
    path('portfolio_compare/', views.portfolio_compare, name='portfolio_compare'),
    path('delete_crypto/', views.delete_crypto, name='delete_crypto'),
    
    ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cryptocompare.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/cryptocompare/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User

import uuid

class Portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image_url = models.URLField( max_length=50, blank = True, null = True)
    coin_name = models.CharField( max_length=50, blank = True, null = True)
    ticker = models.CharField(max_length=50, blank = True, null = True)
    current_price = models.DecimalField(default=0, max_digits=40, decimal_places=20)
    volume = models.IntegerField(default=0)
    high_price = models.DecimalField(default=0, max_digits=40, decimal_places=20)
    low_price = models.DecimalField(default=0, max_digits=40, decimal_places=20)

    def __str__(self):
         return self.coin_name

mysite/cryptocompare/forms.py
from django import forms
from .models import Portfolio
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

mysite/cryptocompare/views.py
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
import requests
import json
from django.contrib.auth.views import LoginView  
from django.contrib import messages
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.edit import DeleteView
from django.contrib.auth.decorators import login_required
from django.core.exceptions import MultipleObjectsReturned, ValidationError
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect, HttpResponseRedirect
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from .models import Portfolio
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.generic.edit import DeleteView
from django.contrib.auth.forms import UserCreationForm


# Crypto List with name, current price, and symbol

def home(request):
    api = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
    raw_data=requests.get(api).json()
    return render(request, 'crypto/home.html', context={'datas':raw_data})  


def register(request):
    if request.method == 'POST':
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid:
                form.save()
                return redirect('cryptocompare:portfolio_compare')
    else:
        form = UserCreationForm()
    return render(request, 'crypto/register.html', {'form':form})


def crypto_login(request):
    api = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
    raw_data=requests.get(api).json()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username , password = password)
        if user is not None:
            login(request , user)
            return redirect('cryptocompare:portfolio_compare')   
        else:
            messages.success(request, 'Wrong password.')
            return redirect('cryptocompare:crypto_login')
    return render(request, 'crypto/crypto_login.html', context={'datas':raw_data})


@login_required(login_url='/crypto_login/')
def logout(request):
    logout(request)
    return redirect(request, '/')


@login_required(login_url='/crypto_login/')
def crypto_list(request):
    api = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
    raw_data=requests.get(api).json()
    return render(request, 'crypto/crypto_list.html', context={'datas':raw_data}) 


@login_required(login_url='/crypto_login/')
def portfolio_compare(request):
    print('hi')
    if request.method == 'POST':
        coin_name=request.POST.get('coin_name')
        if coin_name is not None:
            try:
                Portfolio.objects.get_or_create(user=request.user, coin_name=coin_name)     
            except:
                MultipleObjectsReturned
            return redirect('cryptocompare:portfolio_compare')                
    else:
        portfolio_objs=Portfolio.objects.filter(user=request.user)
        portfolio_list=[]
        portfolio_image=[]
        portfolio_pricelist=[]
        portfolio_daylist=[]
        portfolio_percentdaylist=[]
        portfolio_dayhighlist=[]
        portfolio_daylowlist=[]        
        
        for obj in portfolio_objs:
            coin_api=f'https://api.coingecko.com/api/v3/coins/{obj.coin_name}'
            raw_data_single=requests.get(coin_api).json()
            current_price=raw_data_single['market_data']['current_price']['usd']
            price_change_24h=raw_data_single['market_data']['price_change_24h']
            price_change_percentage_24h=raw_data_single['market_data']['price_change_percentage_24h']
            portfolio_dayhigh=raw_data_single['market_data']['high_24h']['usd']
            portfolio_daylow=raw_data_single['market_data']['low_24h']['usd']
            image=raw_data_single['image']['small']
            portfolio_list.append(obj.coin_name)
            portfolio_image.append(image)
            portfolio_pricelist.append(current_price)
            portfolio_daylist.append(float(price_change_24h))
            portfolio_percentdaylist.append(float(price_change_percentage_24h))
            portfolio_dayhighlist.append(float(portfolio_dayhigh))
            portfolio_daylowlist.append(float(portfolio_daylow))
        final_list = zip(portfolio_list,portfolio_image, portfolio_pricelist,portfolio_dayhighlist, portfolio_daylowlist, portfolio_daylist, portfolio_percentdaylist)
    return render(request, 'crypto/portfolio_compare.html', {'final_list':final_list})

@login_required(login_url='/crypto_login/')
def delete_crypto(request):
    if request.method == "POST":
        try:
            clear_crypto = Portfolio.objects.all()
            clear_crypto.delete()
            return HttpResponseRedirect('cryptocompare:portfolio_compare')           
        except:
            None
            print('none')
        return redirect('cryptocompare:portfolio_compare')

mysite/cryptocompare/templates/base.html
{% load static %}
   
    <!doctype html>
    <html lang="en">
      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'cryptocompare/stylesheet.css' %}">
      </head>
     
          
          {% include 'navbar.html' %}
        
          <div class="container">
            <p class="bg-primary"></p>
            <body>
        {% block content %}
        
        
        
        {% endblock %}</p>
            </div>


        <!-- Optional JavaScript; choose one of the two! -->
    
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        -->
    </body>
    </html>






</body>


</html>

mysite/cryptocompare/templates/crypto/crypto_list.html
{% extends 'base.html' %}
{% load humanize %} 
{% block title %}Crypto List{% endblock %}


{% block content %}


<div class = "jumbotron">
  <center><h1>Top 100 Crypto </h1></center>
</div>
<div class="container mt-3"></div>
  <div class="table-responsive">
    <table class = "table table-dark table-hover">
  

  <thead>
 
    <tr>

        <th scope="col">Logo</th>
        <th scope="col">Name</th>
        <th scope="col">Ticker</th>
        <th scope="col">Market Cap</th>
        <th scope="col">Market Cap Rank</th>
        <th scope="col">Price</th>
        <th scope="col">Volume</th>
  </tr>
</thead>
<tbody>
{% if datas %}

{% for data in datas %}
  <tr>
 
            </div></td>
            <td><img src="{{ data.image }}" height="50px" alt="Coin Logo"></td>
            <td class ="align-middle">{{ data.name }}</td>
            <td class ="align-middle">{{ data.symbol }}</td>
            <td class ="align-middle">${{ data.market_cap }}</td>
            <td class ="align-middle">{{ data.market_cap_rank }}</td>
            <td class ="align-middle">${{ data.current_price }}</td>
            <td class ="align-middle">${{ data.total_volume }}</td>
          </tr>
            {% endfor %}
            {% else %}
            
            <p>Nothing to show</p>
            {% endif %}
  
    </tbody>
  </table>
</div>


{% endblock %}

mysite/cryptocompare/templates/crypto/crypto_login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

    <h1>Login to Crypto Made Easy</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label class="useremail" >Username:</label>
      <input type="text" placeholder="UserName" class="form-control" name="username" autofocus="" required id="id_username">
   </div>
   <div class="form-group">
      <label class="useremail" >Password:</label>
      <input class="form-control" id="id_password" placeholder="Password" type="password" name="password" required>
   </div>
   <button class="btn btn-primary btn-block waves-effect waves-light" type="submit">Login</button>
</form>
</div>
</div> 
</div>
</div>
{% endblock %}

mysite/cryptocompare/templates/crypto/delete_crypto.html
{% extends 'base.html' %}





{% block content %}
{% if user.is_authenticated %}

<div class="main">
    <!-- Create a Form -->
    <form method="post">{% csrf_token %}
        <!-- Security token by Django -->
        
        <p>Are you sure you want to delete ?</p>
    <input type="submit" value="Confirm" />
</form>
{% endif %}
{% endblock %}

mysite/cryptocompare/templates/crypto/home.html
{% extends 'base.html' %}

{% block content %}


<div class="d-grid gap-2 col-6 mx-auto">
    <a class="nav-link active" aria-current="page" href="{% url 'cryptocompare:crypto_login' %}">
      <button type="submit" class="btn btn-primary btn-lg" value="Login">Login</button>

</div>
<div class="d-grid gap-2 col-6 mx-auto">
    <a class="nav-link active" aria-current="page" href="{% url 'cryptocompare:register' %}">
      <button type="submit" class="btn btn-primary btn-lg" value="Register">Register</button>
</div>



                {% if datas %}

                {% for data in datas %}
                
                    <img src="{{ data.image }}" alt="">

                {% endfor %}
                
                
               
                {% endif %}



  {% endblock %}

mysite/cryptocompare/templates/crypto/portfolio_compare.html
{% extends 'base.html' %}
{% load humanize %} 
{% block content %}

<div class = "jumbotron">
  <h1><center>Compare! </h1></center>
</div>

<table class = "table table-dark table-hover">
  

  <thead>
 
    <tr>

        <th scope="col">Name</th>
        <th scope="col">Logo</th>
        <th scope="col">Price</th>
        <th scope="col">High</th>
        <th scope="col">Low</th>
        <th scope="col">Day Change</th>
        <th scope="col">Percent Day Change</th>


</thead>
<tbody>
  {% if user.is_authenticated %} 
      {% for coin_name, image, price, high, low, daychange, daypercentchange in final_list %}
                      
            <td class ="align-middle">{{ coin_name }} </td>
            <td class ="align-middle"><img src="{{ image }}" height="50px" alt="Coin Logo"></td>
            <td class ="align-middle">${{ price }}</td>
            <td class ="align-middle">${{ high }}</td>
            <td class ="align-middle">${{ low }}</td>
            <td class ="align-middle">${{ daychange }}</td>
            <td class ="align-middle">{{ daypercentchange }}%</td>
            </div>
    </tr>
    {% endfor %}
    </tbody>
   
  </table></div>
 
     <!-- Button to Open the Modal -->
  <div class="btn-group text-center ">
 <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal">
   Add Crypto to Compare</button>
  </div>
  <div class="btn-group text-center">
    <form action="{% url 'cryptocompare:delete_crypto' %}" method="POST">
    {% csrf_token %}
      <button type="submit" class="btn btn-danger" value="Clear">Clear Selections</button>
  </form>
</div>
<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Please enter full Crypto name below in lower case letters</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form method="POST" >
          {% csrf_token %}
          <div class="form-group">
            <label for="coin_name"></label>
            <input type="text" class="form-control" id="coin_name" placeholder="cryptoname" name="coin_name">
          </div>
          <button type="submit" class="btn btn-success">Add</button>
        </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
      
 
 
  {% endif  %}
{% endblock %}

mysite/cryptocompare/templates/crypto/register.html
{% extends 'base.html' %}



{% block content %}

    <div  style="margin-top: 20%;margin-left:20%">
        <h2>Sign Up</h2>
        <form method="post">
            {% csrf_token %} 
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
    </div>
{% endblock %}

mysite/cryptocompare/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">CryptoME</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'cryptocompare:crypto_list' %}" >Crypto</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'cryptocompare:portfolio_compare' %}">Compare</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href='/'>Logout</a>
          </li>
          {% endif  %}
        </ul>
      </div>
    </div>
  </nav>